name: Sokol Shader Examples

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  sokol-shaders-can-be-compiled:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update;
          sudo apt-get install --quiet -y libglfw3 libglfw3-dev libfreetype6-dev  libxi-dev libxcursor-dev libasound2-dev xfonts-75dpi xfonts-base
      - name: Build v
        run: |
          echo $VFLAGS
          make -j4
          ./v -cg -cflags -Werror -o v cmd/v
      - name: Shader examples can be build
        run: |
          wget https://github.com/floooh/sokol-tools-bin/archive/pre-feb2021-api-changes.tar.gz
          tar -xf pre-feb2021-api-changes.tar.gz
          for f in examples/sokol/02_cubes_glsl/cube_glsl \
              examples/sokol/03_march_tracing_glsl/rt_glsl \
              examples/sokol/04_multi_shader_glsl/rt_glsl_puppy \
              examples/sokol/04_multi_shader_glsl/rt_glsl_march \
              examples/sokol/05_instancing_glsl/rt_glsl_instancing \
              ; do \
                 echo "compiling shader $f.glsl ..."; \
                 sokol-tools-bin-pre-feb2021-api-changes/bin/linux/sokol-shdc --input $f.glsl --output $f.h --slang glsl330 ; \
          done
          for vfile in examples/sokol/0?*/*.v; do echo "compiling $vfile ..."; ./v $vfile ; done
